# Generated by Django 4.2 on 2024-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_like_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
